# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-24 00:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='middle_name',
            new_name='other_name',
        ),
    ]
