# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-08 15:47
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0002_auto_20180208_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
