# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-24 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0002_auto_20180124_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdebate',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
