# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-24 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0003_auto_20180124_0152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='height',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='optional_image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='width',
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, help_text='Tell us a little about yourself.', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='images/profile/', verbose_name='Profile Picture'),
        ),
    ]
