# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-24 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0004_auto_20180124_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='mobile_no',
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.ImageField(blank=True, help_text='Add Pictures', null=True, upload_to='attachments/debate', verbose_name='Image Attachments'),
        ),
    ]
