# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-28 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0005_auto_20180124_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdebate',
            name='summary',
            field=models.TextField(help_text="Enter a brief summary. <a href='http://commonmark.org/help/' target='_blank'>Markdown <a/> and <a target='_blank' href='https://math.meta.stackexchange.com/questions/5020/mathjax-basic-tutorial-and-quick-reference'>MathJax</a> supported.", max_length=1000, verbose_name='What is your inspiration for the debate?'),
        ),
    ]
