# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-01 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import markdownx.models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0006_auto_20180128_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkdownPostDebate',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('debate.postdebate',),
        ),
        migrations.AlterField(
            model_name='postdebate',
            name='debate_category',
            field=models.CharField(choices=[('open', 'open'), ('closed', 'closed')], default='open', help_text='Open debates do not require predefined debaters and judges. Reverse for closed debates.', max_length=6),
        ),
        migrations.AlterField(
            model_name='postdebate',
            name='summary',
            field=markdownx.models.MarkdownxField(help_text="<a href='http://commonmark.org/help/' target='_blank'>Markdown <a/> and <a target='_blank' href='https://math.meta.stackexchange.com/questions/5020/mathjax-basic-tutorial-and-quick-reference'>MathJax</a> supported. You can     drag images here from your desktop.", max_length=1000, verbose_name='What is your inspiration for the debate?'),
        ),
        migrations.AlterField(
            model_name='postdebate',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='scores',
            name='observation',
            field=markdownx.models.MarkdownxField(blank=True, help_text='Give brief summary of scores. Markdown supported.', max_length=1000, null=True),
        ),
    ]
