# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-03 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0008_auto_20180202_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdebate',
            name='allow_follower_comments',
            field=models.BooleanField(default=True, verbose_name='Can not participants comment after debate?'),
        ),
    ]
