# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-03 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0009_postdebate_allow_follower_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postdebate',
            name='allow_follower_comments',
        ),
        migrations.AddField(
            model_name='postdebate',
            name='allow_follower_comment',
            field=models.BooleanField(default=True, verbose_name='Can non participants comment after debate?'),
        ),
    ]
