# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-08 08:33
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=markdownx.models.MarkdownxField(verbose_name='Body of the blog post'),
        ),
    ]
