# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-01 07:13
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('discourse', '0002_auto_20180124_0152'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkdownPost',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('discourse.post',),
        ),
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=markdownx.models.MarkdownxField(help_text="Be brief and cogent. Keep it hot. <a href='http://commonmark.org/help/' target='_blank'>Markdown <a/> and <a target='_blank' href='https://math.meta.stackexchange.com/questions/5020/mathjax-basic-tutorial-and-quick-reference'>MathJax</a> supported. You can                     drag images here from your desktop.", max_length=1000, verbose_name='What are we discussing today?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
