# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-12 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkcomments', '0003_tkcomment_anonymous_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tkcomment',
            name='comment_anonymous',
            field=models.CharField(blank=True, choices=[('BE_YOURSELF', 'BE YOURSELF'), ('BE_ANONYMOUS', 'BE ANONYMOUS')], help_text='comment as anonymous', max_length=12, null=True, verbose_name='Is this comment an anonymous comment'),
        ),
    ]
